In [1]:
import torch

In [2]:
# back propogation detaylı anlatımı
# https://devhunteryz.wordpress.com/2018/06/20/geri-yayilimbackpropagation/

In [22]:
x=torch.tensor(4.0,requires_grad=True) # requires_grad=True ile geri yayılım yapabiliriz.
x

tensor(4., requires_grad=True)

In [23]:
y=x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [24]:
# Back Propogation y= 2*x
# bu işlem aslında bir türev işlemidir ve geri yayılım yapıldığında bağımsız değişken en başta verilen fonksiyonun
# türevine göre tekrar hesaplanır. (ilk fonksiyon: y=x**2 , geri yayılımla beraber: y=2*x)
y.backward()

In [25]:
print(x.grad)# x=tensor(4., requires_grad=True) idi. y.backward() yani geri yayılımdan sonra fonksiyon y=2*x olunca x de 8 oldu.

tensor(8.)


In [26]:
lst=[[2.,3.,1.],[3.,4.,7.],[5.,2.,3.]]
torch_input=torch.tensor(lst,requires_grad=True)
torch_input

tensor([[2., 3., 1.],
        [3., 4., 7.],
        [5., 2., 3.]], requires_grad=True)

In [27]:
# torch_input için yeni fonskiyonumuz y=x**3+x**2 olsun
# geri yayılımla beraber y=3*x**2+2*x olur.
y=torch_input**3+torch_input**2

In [28]:
y

tensor([[ 12.,  36.,   2.],
        [ 36.,  80., 392.],
        [150.,  12.,  36.]], grad_fn=<AddBackward0>)

In [29]:
z=y.sum()
z

tensor(756., grad_fn=<SumBackward0>)

In [30]:
z.backward()

In [31]:
torch_input.grad #burada oluşan sayılar y=3*x**2+2*x e göre hesaplanmıştır.

tensor([[ 16.,  33.,   5.],
        [ 33.,  56., 161.],
        [ 85.,  16.,  33.]])