In [3]:
import torch
import numpy as np

In [5]:
torch.__version__,np.__version__

('1.9.0', '1.20.1')

###  Numpy array v List 
Ortak bir başlangıç sorusu, buradaki gerçek farkın ne olduğudur. Cevap performanstır. Numpy veri yapıları şu durumlarda daha iyi performans gösterir:

- Boyut - Numpy veri yapıları daha az yer kaplar
- Performans - hıza ihtiyaçları var ve listelerden daha hızlılar
- İşlevsellik - SciPy ve NumPy, yerleşik doğrusal cebir işlemleri gibi optimize edilmiş işlevlere sahiptir.
 

In [12]:
lst=[3,4,5,6]
arr=np.array(lst)

In [13]:
arr

array([3, 4, 5, 6])

In [14]:
arr.dtype

dtype('int32')

### Convert Numpy To Pytorch Tensors

"tensors=torch.from_numpy(arr)"
ifadesi ile <b>hem dizi hem de oluşturulan tensor aynı hafızayı paylaşır</b>. Eğer birisi üzerinde bir değişiklik yaparsak her ikiside bundan etkilenir. <b>Bundan kurtulmanın yolu "tensors = torch.tensor(arr)" ifadesidir.</b>

In [15]:
# Paylaşımlı bellek
tensors=torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [16]:
tensors[3]=100

In [17]:
tensors

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [18]:
arr

array([  3,   4,   5, 100])

In [19]:
# Paylaşımsız bellek (Kopya oluşturma)
tensor_arr=torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [21]:
tensor_arr[3]=6
tensor_arr

tensor([3, 4, 5, 6], dtype=torch.int32)

In [22]:
arr

array([  3,   4,   5, 100])

In [24]:
# create zeros and ones tensors
torch.zeros(2,3,dtype=torch.float64) # 2 boyutlu 2*3 şeklinde 0 lar matrisi oluşturur.

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [25]:
torch.ones(2,3,dtype=torch.float64) # 2 boyutlu 2*3 şeklinde 1 ler matrisi oluşturur.

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [36]:
a=torch.tensor(np.arange(0,15).reshape(5,3)) # 0-15 arasında sayıları içeren 5*3 şeklinde matris oluşturur.
print(a)
print(a[:,0:1])
print(a[:,0:2])

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)
tensor([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12]], dtype=torch.int32)
tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]], dtype=torch.int32)


### Arithmetic İşlemler

In [37]:
a=torch.tensor([3,4,5],dtype=torch.float)
b=torch.tensor([4,5,6],dtype=torch.float)
print(a+b)

tensor([ 7.,  9., 11.])


In [38]:
torch.add(a,b) # toplama

tensor([ 7.,  9., 11.])

In [39]:
c= torch.zeros(3)
c

tensor([0., 0., 0.])

In [40]:
torch.add(a,b,out=c) # a+b=c
c

tensor([ 7.,  9., 11.])

In [42]:
torch.add(a,b).sum() # 7+9+11

tensor(27.)

### Matris Çarpımları

In [43]:
x= torch.tensor([3,4,5], dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)

In [44]:
x.mul(y) # x*y

tensor([12., 20., 30.])

In [45]:
x.dot(y) # (3*4)+(4*5)+(5*6) = 62

tensor(62.)

In [46]:
# Matrix Multiplication

In [47]:
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype=torch.float)

In [48]:
# 1.Metod
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [50]:
# 2.Metod
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [52]:
# 3.Metod
x@y

tensor([[55., 53.],
        [90., 92.]])